### ISSUE TITLE
no callback on Contacts.addContact(contact);

### ISSUE THREAD

**Issue by Mister-Hope** [SunnyApp/flutter_contact#1]
In my project, when I call `Contacts.addContact(contact)`, it is working ,but whether I use `await` or `then`, the code below / call back funtion is not being called. Also, no message is given in the console

I wounder if you could check it.

```
void xxx() async {
 print('start');
await Contacts.addContact(contact);
print('success');
}
```

**Comment by timekone** [comment]
I have the same problem.
Interestingly enough, the contact gets added successfully to device's contact list anyway.

**Comment by Mister-Hope** [comment]
> I have the same problem.
> Interestingly enough, the contact gets added successfully to device's contact list anyway.

Then it seems to be a bug.

**Comment by ericmartineau** [comment]
Are you seeing this for iOS?  Android?  Both?

**Comment by ericmartineau** [comment]
I found an issue on Android.  Try version `0.5.1`

**Comment by Mister-Hope** [comment]
Only Android :sweat_smile: I am a poor guy who can not afford a mac

**Comment by ericmartineau** [comment]
@Mister-Hope Did version 0.5.1 fix it?
