### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(

### ISSUE THREAD

**Issue by kw2019ltd** [SunnyApp/flutter_contact#10]
I/System.out( 4900): Unable to fetch contact image: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object referenceIgnoring mime: vnd.android.cursor.item/nickname

**Comment by ericmartineau** [comment]
@kw2019ltd can you provide any more info on what was happening at the time?

**Comment by ericmartineau** [comment]
I believe I found the issue with this one
