### ISSUE TITLE
 PlatformException was thrown: PlatformException(notFound, in method getContact: Expected a single result for 

### ISSUE THREAD

**Issue by kw2019ltd** [SunnyApp/flutter_contact#11]
I/flutter ( 4900): Flutter error caught by Crashlytics plugin:
I/flutter ( 4900): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter ( 4900): The following PlatformException was thrown:
I/flutter ( 4900): PlatformException(notFound, in method getContact: Expected a single result for contact 824, but
I/flutter ( 4900): instead found 0, co.sunnyapp.flutter_contact.MethodCallException: notFound: in method getContact:
I/flutter ( 4900): Expected a single result for contact 824, but instead found 0)
I/flutter ( 4900): 
I/flutter ( 4900): When the exception was thrown, this was the stack:
I/flutter ( 4900): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter ( 4900): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
I/flutter ( 4900): <asynchronous suspension>
I/flutter ( 4900): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter ( 4900): #3      ContactService.addContact (package:flutter_contact/contacts.dart:180:32)
I/flutter ( 4900): #4      addContact (package:barcodeapp/utils/utils.dart:414:29)
I/flutter ( 4900): <asynchronous suspension>
I/flutter ( 4900): #5      ContactCodeListTile.build.<anonymous closure> (package:barcodeapp/widget/qr_barcode/qrcode_valuetype/common_widget.dart:257:33)
I/flutter ( 4900): <asynchronous suspension>
I/flutter ( 4900): #6      ContactCodeListTile.build.<anonymous closure> (package:barcodeapp/widget/qr_barcode/qrcode_valuetype/common_widget.dart)
I/flutter ( 4900): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
I/flutter ( 4900): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
I/flutter ( 4900): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 4900): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
I/flutter ( 4900): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
I/flutter ( 4900): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
I/flutter ( 4900): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter ( 4900): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter ( 4900): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter ( 4900): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter ( 4900): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter ( 4900): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter ( 4900): #22     _invoke1 (dart:ui/hooks.dart:275:10)
I/flutter ( 4900): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
I/flutter ( 4900): (elided 3 frames from dart:async)
I/flutter ( 4900): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/CrashlyticsPlugin( 4900): Unable to generate stack trace element from Dart side error.
I/flutter ( 4900): firebase_crashlytics: Error reported to Crashlytics.

**Comment by ericmartineau** [comment]
Can you provide more info?
