### ISSUE TITLE
 UIKit.UIActivityIndicatorView:6:12: note: 'init(style:)' was introduced in Swift 4.2

### ISSUE THREAD

**Issue by tkeithblack** [SunnyApp/flutter_contact#12]
Installed flutter_contact 0.5.2 and received Swift compile error:

 UIKit.UIActivityIndicatorView:6:12: note: 'init(style:)' was introduced in Swift 4.2
        public init(style: UIActivityIndicatorViewStyle)

To address this I manually opened my xCode project and updated flutter_contact to use Swift Language 4.2. Probably need to update the flutter_contact.podspec file.

**Comment by ericmartineau** [comment]
Fixed in flutter_contact 0.5.4

**Comment by ericmartineau** [comment]
PS. Thanks for the PR.
