### ISSUE TITLE
Add contacts through native form

### ISSUE THREAD

**Issue by timekone** [SunnyApp/flutter_contact#2]
Thank you for a great package! ❤️
Does it support adding contacts via device form? 
See pull request [#69](https://github.com/lukasgit/flutter_contacts/pull/69) in flutter_contacts package for reference.
It would be awesome to have such feature.

**Comment by ericmartineau** [comment]
This isn't currently supported, but that PR looks like it could be added to this project pretty easily

**Comment by ericmartineau** [comment]
@timekone see `v0.5.2`
