### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Astalavist4** [SunnyApp/flutter_contact#30]
Hi,

Nice work. Really appreciate your work.

I am getting below dump when trying to update a contact.

Attempt to invoke interface method 'int org.joda.time.format.InternalParser.parseInto(org.joda.time.format.DateTimeParserBucket, java.lang.CharSequence, int)' on a null object reference, java.lang.NullPointerException: Attempt to invoke interface method 'int org.joda.time.format.InternalParser.parseInto(org.joda.time.format.DateTimeParserBucket, java.lang.CharSequence, int)' on a null object reference, null))

**Comment by deezaster** [comment]
I have the same problem. But only with Android. With IOS it works.

**Comment by ericmartineau** [comment]
This should be fixed in the latest release  `0.6.4+1`
