### ISSUE TITLE
Couldn't add a custom label to contact's phones.

### ISSUE THREAD

**Issue by hmarat** [SunnyApp/flutter_contact#38]
Anytime when I want to change contact's phone label to custom, it changes to "Other".

contact.phones[0].label = 'Custom label';
await Contacts.updateContact(contact);

![image](https://user-images.githubusercontent.com/55658812/102009647-4a69ea80-3d52-11eb-9a0d-466d6c418f3f.png)

**Comment by ericmartineau** [comment]
0.6.5+1

**Comment by ericmartineau** [comment]
This wasn't implemented on Android on account of my laziness.

It should be now.  `0.6.5+1`
