### ISSUE TITLE
A compilation error

### ISSUE THREAD

**Issue by babonka** [SunnyApp/flutter_contact#39]
When I'm adding plugin to my project I received a compilation error.
`flutter_contact-0.6.4+2/android/src/main/kotlin/co/sunnyapp/flutter_contact/FlutterContactPlugin.kt: (177, 47): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Uri?`

I changed string 177 to
`val contactId = saveResult.first().uri?.lastPathSegment?.toLong()` locally.

Please make changes in repo.
FYI. I use Kotlin 1.3.50

**Comment by ericmartineau** [comment]
Fixed in `0.6.4+5`
