### ISSUE TITLE
'package:sunny_dart/time/date_components.dart': Failed assertion: line 48 pos 12: 'input != null': Input must not be null

### ISSUE THREAD

**Issue by dheerajsarwaiya** [SunnyApp/flutter_contact#4]
```
         final contacts = Contacts.listContacts(
          sortBy: ContactSortOrder.firstName(),
          withHiResPhoto: false,
          withThumbnails: false,
          // bufferSize: 20
        );
        final total = await contacts.length;
        int counter = 1;
        while (counter < total - 1) {
          // print(counter);
          try {
            final contact = await contacts?.get(counter) ?? null;
            print((contact?.identifier ?? "") + ":" + contact?.displayName);
          } catch (error) {
            print(error);
          }
          counter++;
        }
```

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:sunny_dart/time/date_components.dart': Failed assertion: line 48 pos 12: 'input != null': Input must not be null

I am getting the error randomly, irrespective of how I sort it or what function I use (streamContacts). 

There is no issue with the permission. I used permission_handler to get the contact permission. I have update AndroidMainfest.xml file but still getting the error.

What am I missing?

**Comment by ericmartineau** [comment]
Should be fixed in 0.5.5
