### ISSUE TITLE
Why iOS 12?

### ISSUE THREAD

**Issue by acoutts** [SunnyApp/flutter_contact#43]
Why is iOS 12 the deployment minimum requirement?

**Comment by acoutts** [comment]
Submitted https://github.com/SunnyApp/flutter_contact/pull/44 to lower it back to 9.0.

**Comment by ycherniavskyi** [comment]
I have the same question - is iOS 12 really necessary for this plugin?

**Comment by ycherniavskyi** [comment]
Do plugin developers have any concerns about lowing the required iOS version?

@ericmartineau could you please clarify why you increase minimal iOS version in commit 07fb91d2e6c993a3f33f6f4f86ca3194147dda76 (which from description related to android 😊)?

**Comment by ericmartineau** [comment]
To be honest, I don't recall.  I'll look into it

**Comment by ericmartineau** [comment]
I believe this is bumped back to 9.
