### ISSUE TITLE
openContactInsertForm only parsing phone number

### ISSUE THREAD

**Issue by kadersaka** [SunnyApp/flutter_contact#47]
![image](https://user-images.githubusercontent.com/26827426/108944615-63005600-765b-11eb-9e69-965473c62bd8.png)
![WhatsApp Image 2021-02-24 at 04 52 36](https://user-images.githubusercontent.com/26827426/108945069-3c8eea80-765c-11eb-9315-61d4411bea69.jpeg)
When i call "openContactInsertForm " and i pass it my contact object, it only parse the phone number and the email, other fields (displayName, givenName , familyName...)  are not parsed, even with your library's example project.

**Comment by ericmartineau** [comment]
I tried to use the ContactsContract.Intents.Insert.DATA field, but I could never get it to work properly.  I did make a change so that it will use given/family or displayName, depending on which has values.  That should get the name to show up at least.
