### ISSUE TITLE
Please update dependencies for compatibility with Flutter 2.0/null safety packages

### ISSUE THREAD

**Issue by tkeithblack** [SunnyApp/flutter_contact#49]
I've been upgrading many packages to the null safety versions. I ran across a couple of dependencies in flutter_contacts that cause conflicts. I think these would be very easy to bump.

First, there is uuid ^2.2.2 which needs to update to uuid: ^3.0.1. 
NOTE: I noticed in the code that the only reference to UUID is in your test code, so you can probably move it out of the main dependencies section.

Second is updating from sunny_dart: ^0.5.8+5 to sunny_dart: ^0.6.0+4

Thanks for providing this very useful package!

**Comment by ericmartineau** [comment]
Will do

**Comment by tkeithblack** [comment]
I ran into another one: 

logging: ^1.0.0

Thanks!

**Comment by ericmartineau** [comment]
OK, I have a pre-release version with null-safety `0.7.5+1` that includes upgrades for all libraries.  I actually cleaned out dependencies except the basics.

**Comment by tkeithblack** [comment]
Thank you, I'll give it a try!
