### ISSUE TITLE
Contacts are returned in random order

### ISSUE THREAD

**Issue by fedotxxl** [SunnyApp/flutter_contact#5]
Hello. I tried to use ordering but it returns contacts with some unpredictable order for me. Finally, I changed in `ContentResolver.queryContacts` query to

`
 return query(ContactsContract.Data.CONTENT_URI, projections, selection, selectionArgs, "upper("+ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME + ") ASC")
`

copied from https://stackoverflow.com/a/24489525/716027
I think ordering by display name is the most common case. Can you add it?

**Comment by ericmartineau** [comment]
Sorry for the terribly late response, but can you provide more info about what you were seeing that prompted the change?

**Comment by ericmartineau** [comment]
I believe this is fixed.
