### ISSUE TITLE
ios contact note don't show as expect.

### ISSUE THREAD

**Issue by hustjiangtao** [SunnyApp/flutter_contact#53]
edit a contact with note: 

![image](https://user-images.githubusercontent.com/13832759/111759396-7e682500-88d8-11eb-8631-08bda4400fbb.png)

and not show on contact info written by flutter_contact.

![image](https://user-images.githubusercontent.com/13832759/111759530-a788b580-88d8-11eb-8526-2737c8ac0234.png)

flutter code similar to flutter_contact sample demo.

expect way to solve it or the reason about it?

**Comment by hustjiangtao** [comment]
By the way android doesn't have this problem.

**Comment by ericmartineau** [comment]
ios added restrictions in v13 where contact notes is an extra entitlement that requires special approval from apple.  So, unfortunately, that means that notes will not work in ios
