### ISSUE TITLE
label for dates on Android

### ISSUE THREAD

**Issue by Billy-80** [SunnyApp/flutter_contact#56]
Hello, on Android when using  Contacts.updateContact(contact); , the labels for dates are changed / duplicated ( see the screenshot). The plugin update function after deletion and at insertion is done with date.label (.withTypeAndLabel(ItemType.event, date.label), this seems to modify the existing labels for birthday , even when the string is passed as 'Birthday' with an upper case 'B', this is still perceived by Android as a user custom label text. 

Also if the contact had an anniversary event date already set, after update the anniversary duplicates the event due to the label mismatch.
This can be reproduced by updating a field for an existing contact ( any field) which already has a date set for an event on android 10 or 11 emulator.

According to the [link](https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.CommonColumns#LABEL) ,it seems that the type of data needs to be passed as an integer ( like EVENT.LABEL.TYPE_BIRTHDAY for instance).

![Screenshot 2021-04-08 at 12 24 40](https://user-images.githubusercontent.com/69310100/114002404-824aef80-9865-11eb-9fe8-b045559328ee.png)

**Comment by ericmartineau** [comment]
Fixed - the reverse type mapping was a copy/paste mistake and hadn't been updated.  Should be fixed in:
`flutter_contact: ^0.9.1+6`
