### ISSUE TITLE
"withThumbnails: false" doesn't work

### ISSUE THREAD

**Issue by abhinavsingh** [SunnyApp/flutter_contact#59]
We are using `flutter_contact: ^0.8.1+2` as follows:

```
var contacts = Contacts.streamContacts(
    withThumbnails: false,
    withHiResPhoto: false,
    withUnifyInfo: false,
    bufferSize: CONTACTS_BUFFER_SIZE,
  );
```

But returns `contacts` still return the thumbnail data.

Are we missing something here or is it a bug?

**Comment by ericmartineau** [comment]
fixed 
`flutter_contact: ^0.9.1+7`
