### ISSUE TITLE
Update needed to use flutter_contact with flutter_local_notifications plugin

### ISSUE THREAD

**Issue by abhinavsingh** [SunnyApp/flutter_contact#72]
1. `flutter_contact` depends upon https://github.com/ericmartineau/flexidate (which no longer seem to exist).
2. `flexidate >=0.6.0+2` depends on `timezone ^0.7.0`
3. `flutter_local_notifications ^8.1.1+2` which depends on `timezone ^0.8.0`

As a result flutter build leads into `version solving failed`.

Any idea how to get past this?

**Comment by deepak786** [comment]
Override the timezone dependency. It will solve the issue.

```
dependency_overrides:
    timezone: 0.7.0
```

**Comment by abhinavsingh** [comment]
Thank you, didn't realize the `dependency_overrides` flag.
